baseURL: https://zenmau.github.io/lablog/
languageCode: pt-br
title: Lablog
theme: "PaperMod"
paginate: 5

enableEmoji: true
enableInlineShortcodes: true

menu:
  main:
    - name: Search
      url: search/
      weight: 10
    - name: Categories
      url: categories/
      weight: 2
    - name: Tags
      url: tags/
      weight: 3
    - name: Posts
      url: posts/
      weight: 1
    - name: Archives
      url: archives/
      weight: 5
      
params:
  env: prodution
  author: Maurício Ferraz
  title: Lablog
  DateFormat: "02-01-2006"
  defaultTheme: auto
  math: true
  homeInfoParams:
    Title: Lablog
    Content: Um blog para jogar minhas coisas
  socialIcons:
    - name: Instagram
      url: "https://www.instagram.com/maus.p.doc/"
  
  comments: false
  showtoc: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  displayFullLangName: true
  

markup:
    goldmark:
        renderer:
            unsafe: true

